[package]
name = "learn_veilid"
version = "0.1.0"
edition = "2021"
authors = ["Aaron Askew <aaronaskew@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
veilid-core = "0.2.4"
